### ISSUE TITLE
ShadcnUi - the New Ui Toolkit is here are we using this here

### ISSUE THREAD

**Issue by wildgrandma** [Heliumwarlord/AngularCRUD#3]
If u Concur taht Shadcn is a good addition to this project pls let us use them and upgrade this App.

**Comment by Heliumwarlord** [comment]
This is indeed a good addition, But were still on the learning phase of App, will move on to use them in our app in the near future.
![DeWatermark ai_1713632627295](https://github.com/Heliumwarlord/AngularCRUD/assets/125116980/e7bc6445-c673-47df-8193-fe400af9881b)
